---
- hosts: idrac
  connection: local
  name: Get system inventory
  gather_facts: True

  collections:
    - dellemc.openmanage

  tasks:
  - name: Get system inventory.
    idrac_system_info:
       idrac_ip: "{{ inventory_hostname  }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
       validate_certs: False
