---
- hosts: iDRACs
  connection: local
  name: Get system inventory
  gather_facts: False

  collections:
  - dellemc.openmanage

  tasks:
  - name: Get system inventory.
    idrac_system_info:
       idrac_ip: "{{ inventory_hostname }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password: "{{ idrac_password }}"
       validate_certs: false
       #ca_path: "/path/to/ca_cert.pem"
    register: result_syst_inv
  - debug:
        var: result_syst_inv
