---
- hosts: OMEnt
  connection: local
  gather_facts: False
  name: Get a list of the server device IDs.
  
  collections:
    - dellemc.openmanage

  tasks:
    - name: Get a list of all Server devices.
      ome_device_info:
        hostname:  "{{ inventory_hostname }}"
        username: "{{ OME_User }}"
        password:  "{{ OME_Password }}"
        validate_certs: false
        #ca_path: "/path/to/ca_cert.pem"
        system_query_options:
          filter: "Type eq 1000"
      register: result
      delegate_to: localhost
    - name: Get a list of all Server Device IDs
      set_fact:
        devices:  "{{ result.device_info.value | map(attribute='Id') | list }}"
    - debug:
        var: devices
